### ISSUE TITLE
Internal server error while processing request

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#129] opened 2021-06-22 12:55 UTC
I am currently logged in as webdev and the server is unable to store my form submission:

```
SignIn.js:89 user info:  Object
form:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
FormChooser.js:45 existing forms:   {message: "Internal server error while processing request: or…rg.eclipsefoundation.react.model.FormOrganization", status_code: 500}message: "Internal server error while processing request: org.hibernate.HibernateException: More than one row with the given identifier was found: 8aa8931b7a1a3504017a1a756473000b, for class: org.eclipsefoundation.react.model.FormOrganization"status_code: 500__proto__: Object
formFunctionHelpers.js:630 Start with a new form: [{…}]

```

**Comment by autumnfound** [comment] 2021-06-29 13:39
Closing as this is a duplicate of #118

**Closed by autumnfound** 2021-06-29 13:39 UTC
Labels: Backend, bug, top-priority
