### ISSUE TITLE
Can only get 10 existing forms from back end

### ISSUE THREAD

**Issue by linkfang** [EclipseFdn/react-eclipsefdn-members#92] opened 2021-06-03 18:56 UTC
When the user creates more than 10 forms, back end will still send back the first 10 forms.

Here is what in the database: (12 in total)
![image](https://user-images.githubusercontent.com/43075439/120697039-3ab69d80-c47b-11eb-8e66-66ae4b4a829a.png)

Here is what the front end receives: (10 in total)
![image](https://user-images.githubusercontent.com/43075439/120697083-46a25f80-c47b-11eb-81f8-ab1f9532be73.png)

Do we need to support more than 10 existing forms?
If so, I think we can either 
1. Send back all available forms. (Could be too many if user creates quite a lot)
2. Keep 10 items in the array but reverse the order/sequence. Like the first form will be the last item in the array, and the latest form will be the 1st item in the array.

**Comment by autumnfound** [comment] 2021-06-04 13:12
This uses pagination, so you should be able to get the other forms by checking the headers :)

**Comment by linkfang** [comment] 2021-06-04 15:11
> This uses pagination, so you should be able to get the other forms by checking the headers :)

Oh..., OK, I will take a look at it. Thanks Martin!

**Comment by linkfang** [comment] 2021-06-04 18:40
I checked the header and I did see there is a page=1 and page=2 in the response heasers.link

Should I use "https://www.rem.docker/form?page=2" to get the 2nd page? I tried this but got an empty array (I have 14 forms)

**Comment by autumnfound** [comment] 2021-06-14 15:42
To loop back around for transparency, I looked into this and a bad number of results were being returned due to pagination both in the persistence DAO and the response filter that paginates results. To better accommodate this I've made a patch to the commons project to resolve this weird behaviour. It is currently up for review and will be included once approved and is live

**Comment by chrisguindon** [comment] 2021-06-17 17:36
@autumnfound Can you add a link to your PR to the common project so that we can monitor the status?

**Comment by autumnfound** [comment] 2021-06-17 18:00
The PR is merged in, we're blocked by a broken build and I'm waiting for Mika time to discuss how we want to approach it.

**Comment by autumnfound** [comment] 2021-06-17 18:08
Here is the issue tracking this break: https://gitlab.eclipse.org/eclipsefdn/webdev/eclipsefdn-api-common/-/issues/1

**Comment by chrisguindon** [comment] 2021-06-22 14:54
@autumnfound for this use case, the application does not need to paginate the various forms. 

We simply need the latest form or an empty result if this is the first form submission of the user. Could we create a new argument that would allow us to retrieve the 1 form which would be the last once if it exists?

Something like:

/api/form?best=true

**Comment by autumnfound** [comment] 2021-07-19 13:20
@linkfang can you confirm that the fix that was submitted for this is working as intended?

**Comment by autumnfound** [comment] 2021-07-19 18:42
Fixed, live, and confirmed by @linkfang

**Closed by autumnfound** 2021-07-19 18:42 UTC
Labels: Backend, enhancement, top-priority
